spring.application.name=quantity-measurement-app
server.port=8080

# Logging
logging.level.root=INFO
logging.level.com.app.quantitymeasurement=DEBUG

# Swagger
springdoc.swagger-ui.enabled=true

# JWT
jwt.secretKey=${JWT_SECRET:this_is_a_very_long_secret_key_with_more_than_256_bits_of_secure_entropy_for_jwt_hmac_sha256_algorithm_production_level}

# OAuth
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# Actuator
management.endpoints.web.exposure.include=health,metrics



# run -> mvn spring-boot:run -Dspring-boot.run.profiles=dev 